services:
  frontend:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../frontend:/usr/src/app
      - ../shared_prisma:/usr/src/app/prisma
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  admin:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ../admin:/usr/src/app
      - ../shared_prisma:/usr/src/app/prisma
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: