services:
  frontend:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../frontend:/usr/src/app
      - ../shared_prisma:/usr/src/app/prisma
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development

  admin:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ../admin:/usr/src/app
      - ../shared_prisma:/usr/src/app/prisma
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development

  mysql:
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: